### ISSUE TITLE
not able to install

### ISSUE THREAD

**Issue by sujansonly** [juliandunn/oracle-xe#3]
adding the error trace here, im not able to find the issue.

           ---------------------
           # In /tmp/kitchen/cookbooks/oracle-xe/recipes/default.rb

            29: yum_package 'oracle-xe' do
            30:   source ::File.join(Chef::Config[:file_cache_path], 'oracle-xe-11.2.0-1.0.x86_64.rpm')
            31:   action :install
            32: end
            33:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/oracle-xe/recipes/default.rb:29:in `from_file'

           yum_package("oracle-xe") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "oracle-xe"
             source "/tmp/kitchen/cache/oracle-xe-11.2.0-1.0.x86_64.rpm"
             version "11.2.0-1.0"
             timeout 900
             flush_cache {:before=>false, :after=>false}
             declared_type :yum_package
             cookbook_name :"oracle-xe"
             recipe_name "default"
           end

       Running handlers:
       [2015-03-24T20:20:39+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-24T20:20:39+00:00] ERROR: Exception handlers complete
       [2015-03-24T20:20:39+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 1 resources updated in 160.287396275 seconds
       [2015-03-24T20:20:41+00:00] ERROR: yum_package[oracle-xe] (oracle-xe::default line 29) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
       [2015-03-24T20:20:41+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by sujansonly** [comment]
okay i see its complaining about SWAP memory of the machine. How can i ignore swap mem, while installing

**Comment by juliandunn** [comment]
Uh, that's why the `run_list` includes the `oracle-xe_test` cookbook which depends on the `swap` cookbook which sets up some swapspace...

**Comment by sujansonly** [comment]
oh i did not see the dependencies, im able to install the app with some temp swap memory. thanks for the info though.
